project:
  type: website
  output-dir: _site

website:
  title: "Maxime Rivest"
  description: "Personal blog"
  site-url: "https://maximerivest.com"
  navbar:
    right:
      - href: https://twitter.com/maximerivest
        text: Twitter
  page-navigation: true
  repo-url: https://github.com/maximerivest/blog
  repo-actions: [edit]

format:
  html:
    theme:
      light: [cosmo, styles-light.scss]
      dark: [darkly, styles-dark.scss]
    toc: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: false
    code-fold: false
    code-tools: false
