project:
  type: website
  output-dir: _site

website:
  title: "Maxime Rivest"
  description: "Personal blog"
  site-url: "https://maximerivest.com"
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: https://x.com/maximerivest
        icon: twitter
      - href: https://www.youtube.com/@maximerivest
        icon: youtube
      - href: https://github.com/maximerivest
        icon: github
  repo-url: https://github.com/MaximeRivest/maximerivest-blog
  repo-actions: [edit]
  google-analytics: "G-532FMB8ETS" # your Measurement ID

resources:
  - assets
  - posts/**/*.jpg
  - posts/**/*.jpeg
  - posts/**/*.png
  - posts/images

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: custom.css
    #include-after-body:
    #  - text: |
    #      <script src="/assets/js/custom.js" defer></script>
    toc: false
    #css: my_style.css
