name: Deploy Quarto site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/configure-pages@v3
      - run: quarto render
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
      - uses: actions/deploy-pages@v1
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
